title: Fredy.dev | A blog about programming 
email: me@fredy.dev
description: A blog were I write about programming, tutorials, and projects.
url: https://fredy.dev
baseurl: /

permalink: /:categories/:title/

plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-gist
  - jekyll-analytics


jekyll-archives:
  enabled: 
    - categories
    - tags
  layout: archive
  permalinks:
    category: '/category/:name/'
    tags: '/tag/:name/'

social:
  name: Fredy Sandoval
  links:
    - https://twitter.com/fsandovaldev
    - https://github.com/FredySandoval
    - https://dev.to/fredysandoval
    - https://medium.com/@shockerovip
    - https://fredysandoval.hashnode.dev/

gems:
  - jekyll-tagging-related_posts

paginate: 20
paginate_path: "/page:num/"

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: G-M7RTRWEW1C # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking